// This file is generated by npm build-icons
  
  export type IconName =
  | "add-person"
	| "arrow"
	| "bell"
	| "book"
	| "check"
	| "cheveron-down-small"
	| "cheveron-down"
	| "discord"
	| "hashtag-with-speech-bubble"
	| "hashtag"
	| "inbox"
	| "magnifying-glass"
	| "people"
	| "pin"
	| "question-circle"
	| "speaker-phone"
	| "verified"
  